version: "3"

services:
  rxburn-api:
    build: ./api
    container_name: rxburn-api
    ports:
      - "81"
    volumes:
      - ./api/app.py:/app/app.py:ro,Z
      - ./data/store/rxburn.zarr:/app/rxburn.zarr:Z
      #- ./data/preprocessed_polygons.json:/app/preprocessed_polygons.json:ro,Z
    environment:
      - USERNS_MODE=keep-id
      - LOG_LEVEL=info
      - UVICORN_ACCESS_LOG=true
      - REDIS_URL=redis://rxburn-apicache:6379
    depends_on:
      - rxburn-apicache
    networks:
      - rxburn-backend
    ## neccesary so that zarr store can live in drought group directory
    group_add:
      - keep-groups

  rxburn-apicache:
    image: docker.io/redis:7-alpine
    container_name: rxburn-apicache
    networks:
      - rxburn-backend

  rxburn-dashboard:
    image: nginx:1.28.0
    container_name: rxburn-dashboard
    ports:
      - "18087:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html:Z
      - ./dashboard/default.conf:/etc/nginx/conf.d/default.conf:ro,Z
      - rxburn-nginx-cache:/var/cache/nginx/rxburn_data_cache
    environment:
      - USERNS_MODE=keep-id
    depends_on:
      - rxburn-api
    networks:
      - rxburn-backend

## named volume for proxy cache created by nginx server
volumes:
  rxburn-nginx-cache:

networks:
  rxburn-backend:
    driver: bridge
    enable_ipv6: false
